name: Github Actions to release versions
description: release service versions using github action
inputs:
  release_version:
    description: Release Version
    required: true
outputs:
  release_version:
    description: Release Version
runs:
  using: docker
  image: Dockerfile
